# Numpy基础

## 创建数组

* 从列表创建

In [8]:
import numpy as np
np.array([1, 2, 3, 4, 5], dtype='float32')

array([ 1.,  2.,  3.,  4.,  5.], dtype=float32)

In [7]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

* 使用内置函数创建

In [9]:
#创建长度为5的全零数组
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
#创建3*4的浮点型矩阵
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])